version: "3.8"

services:
  db_employee:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_INITDB_SKIP_TZINFO: 1
    restart: always
    ports:
      - "${DB_PORT:-3306}:3306"
    container_name: db_employee
    volumes:
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./db/mysql_data:/var/lib/mysql
    networks:
      - net_employee
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: 250M
        reservations:
          cpus: "0.1"
          memory: 128M

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:5.0.2
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: 3306
    ports:
      - "8080:80"
    networks:
      - net_employee
    depends_on:
      - db_employee
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: 220M
        reservations:
          cpus: "0.1"
          memory: 128M

  app_employee_management:
    build:
      context: .
    container_name: employee_management
    env_file:
      - .env
    volumes:
      -  ~/.m2/repository:/root/.m2/repository
    networks:
      - net_employee
    depends_on:
      - db_employee
      - phpmyadmin
    ports:
      - "${PORT:-8090}:8080"
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: 250M
        reservations:
          cpus: "0.1"
          memory: 128M



networks:
  net_employee:
    driver: bridge
    driver_opts:
      com.docker.netwwork.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        -
          subnet: 192.168.0.1/24
          gateway: 192.168.0.1
        -
          subnet: "2001:0db8:85a3:0000:0000:8a2e:0370:7334/64"
          gateway: "2001:0db8:85a3::1"

