server:
  port: ${PORT}
  servlet:
    context-path: /employee
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc
  pathsToMatch: /**
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect:
          storage_engine: innodb
  data:
    jpa:
      repositories:
        enabled: true
environment:
  user-admin: ${USER_ADMIN}
  pass-admin: ${PASS_ADMIN}
  role-admin: ${ROLE_ADMIN}
  path-permission: ${PATH_FILE_PERMISSION}
  secret-key: ${SECRET_KEY}
  expiration-key: ${EXP_KEY}
