name: DeployApp

on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create file .env
        run: |
          echo "DB_HOST=${{secrets.DB_HOST}}" >> .env
          echo "DB_PORT=${{secrets.DB_PORT}}" >> .env
          echo "DB_NAME=${{secrets.DB_NAME}}" >> .env
          echo "DB_USER=${{secrets.DB_USER}}" >> .env
          echo "DB_PASS=${{secrets.DB_PASS}}" >> .env
          echo "USER_ADMIN=${{secrets.USER_ADMIN}}" >> .env
          echo "PASS_ADMIN=${{secrets.PASS_ADMIN}}" >> .env
          echo "ADMIN_ROLE=${{secrets.ADMIN_ROLE}}" >> .env
          echo "SECRET_KEY=${{secrets.SECRET_KEY}}" >> .env
          echo "EXP_KEY=${{secrets.EXP_KEY}}" >> .env
          echo "PATH_FILE_PERMISSION=${{secrets.PATH_FILE_PERMISSION}}" >> .env
      - name: Build the Docker image
        run: docker compose -f docker-compose.yml up -d

