name: DeployApp

on:
  push:
    branches: [ "main" ]
env:
  DB_HOST: ${{secrets.DB_HOST}}
  DB_PORT: ${{secrets.DB_PORT}}
  DB_NAME: ${{secrets.DB_NAME}}
  DB_USER: ${{secrets.DB_USER}}
  DB_PASS: ${{secrets.DB_PASS}}
  USER_ADMIN: ${{secrets.USER_ADMIN}}
  PASS_ADMIN: ${{secrets.PASS_ADMIN}}
  ADMIN_ROLE: ${{secrets.ADMIN_ROLE}}
  SECRET_KEY: ${{secrets.SECRET_KEY}}
  EXP_KEY: ${{secrets.EXP_KEY}}
  PATH_FILE_PERMISSION: ${{secrets.PATH_FILE_PERMISSION}}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build the Docker image
        run: docker compose -f docker-compose.yml up

